main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),
	path('sneakers/', views.sneakers_index, name='index'),
    path('sneakers/<int:sneaker_id>/', views.sneakers_detail, name='detail'),
    path('sneakers/create/', views.SneakerCreate.as_view(), name='sneakers_create'),
    path('sneakers/<int:pk>/update/', views.SneakerUpdate.as_view(), name='sneakers_update'),
    path('sneakers/<int:pk>/delete/', views.SneakerDelete.as_view(), name='sneakers_delete'),
    path('sneakers/<int:sneaker_id>/add_buyer/', views.add_buyer, name='add_buyer'),
    path('sneakers/<int:sneaker_id>/assoc_lace/<int:lace_id>/', views.assoc_lace, name='assoc_lace'),
    path('laces/', views.LaceList.as_view(), name='laces_index'),
    path('laces/<int:pk>/', views.LaceDetail.as_view(), name='laces_detail'),
    path('laces/create/', views.LaceCreate.as_view(), name='laces_create'),
    path('laces/<int:pk>/delete/', views.LaceDelete.as_view(), name='laces_delete'),
]

sneakerscollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse


LACES = (
  ('L', 'Large'),
  ('M', 'Medium'),
  ('S', 'Small')
)

class Laces(models.Model):
  sizes = models.CharField(
    'Lace Size',
    max_length=1,
    choices=LACES,
    default=LACES[0][0]
  )
  color = models.CharField(max_length=20)

  def __str__(self):
    return f"Size {self.sizes} and Color {self.color}"

  def get_absolute_url(self):
    return reverse('laces_detail', kwargs={'pk': self.id})

# Create your models here.
class Sneaker(models.Model):
  name = models.CharField(max_length=100)
  brand = models.CharField(max_length=100)
  description = models.CharField(max_length=250)
  price = models.IntegerField('Retail Price')
  laces = models.ManyToManyField(Laces)

  def get_absolute_url(self):
      return reverse('detail', kwargs={'sneaker_id': self.id})

SIZES = (
  ('11', 'Size 11'),
  ('10', 'Size 10'),
  ('9', 'Size 9'),
  ('8','Size 8'),
  ('7','Size 7')
)

class Buyer(models.Model):
  name = models.CharField('Buyer Name', max_length=100)
  value = models.IntegerField('Resell Price')
  bought = models.DateField('Date Bought')
  size = models.CharField(
    'Size Bought',
    max_length=2,
    choices=SIZES,
    default=SIZES[0][0]
  )

  sneaker = models.ForeignKey(Sneaker, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_size_display()} on {self.bought}"

  class Meta:
    ordering = ['-bought']

main_app/forms.py
from django.forms import ModelForm
from .models import Buyer

class BuyerForm(ModelForm):
    class Meta:
        model = Buyer
        fields = ['name', 'value', 'bought', 'size']

main_app/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.http import HttpResponse #res.send in express
from .models import Sneaker, Laces #importing our model
from .forms import BuyerForm

class SneakerCreate(CreateView):
    model = Sneaker
    fields = '__all__'

class SneakerUpdate(UpdateView):
    model = Sneaker
    fields = ['brand', 'description', 'price']

class SneakerDelete(DeleteView):
    model = Sneaker
    success_url = '/sneakers/'


def home(request):
    return HttpResponse('<h1>Welcome to Sneaker Collector!</>')

def about(request):
    return render(request, 'about.html')

def sneakers_index(request):
    sneakers = Sneaker.objects.all() # using our model to get all the rows in our cat table in psql
    return render(request, 'sneakers/index.html', {'sneakers': sneakers})

def sneakers_detail(request, sneaker_id): # path('cats/<int:cat_id>/' <- this is where cat_id comes from
    sneaker = Sneaker.objects.get(id=sneaker_id)
    laces_sneaker_doesnt_have = Sneaker.objects.exclude(id__in = sneaker.laces.all().values_list('id'))
    buyer_form = BuyerForm()
    return render(request, 'sneakers/detail.html', {'sneaker': sneaker, 'buyer_form': buyer_form,
    'laces': laces_sneaker_doesnt_have
    })

def add_buyer(request, sneaker_id):
    form = BuyerForm(request.POST)

    if form.is_valid():
        new_buyer = form.save(commit=False)
        new_buyer.sneaker_id = sneaker_id
        new_buyer.save()

    return redirect('detail', sneaker_id=sneaker_id)

def assoc_lace(request, sneaker_id, lace_id):
  Sneaker.objects.get(id=sneaker_id).laces.add(lace_id)
  return redirect('detail', sneaker_id=sneaker_id)


class LaceList(ListView):
  model = Laces

class LaceDetail(DetailView):
  model = Laces

class LaceCreate(CreateView):
  model = Laces
  fields = '__all__'

class LaceDelete(DeleteView):
  model = Laces
  success_url = '/laces/'

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About the Sneaker Collector</h1>
<hr />
<p>Welcome to a collection of sneakers. Where you can add your own!</p>


{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Sneaker Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;SneakerCollector</a></li>
        </ul>
        <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'index' %}">View All Sneakers</a></li>
            <li><a href="{% url 'sneakers_create' %}">Add A Sneaker</a></li>
            <li><a href="{% url 'laces_index' %}">View All Laces</a></li>
            <li><a href="{% url 'laces_create' %}">Add Laces</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Sneaker Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/main_app/laces_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Laces</h1>

  <h4>Are you sure you want to delete <span>{{ object.sizes }}</span> Laces ?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'laces_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/laces_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Laces Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Size: {{ laces.sizes }}</span>
        <p>Color: {{ laces.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'laces_delete' laces.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/laces_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit {{object.sizes}} and {{object.color}}</span></h1>
  {% else %}
    <h1>Add Laces</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>

  <script>
    const selectEl = document.getElementById('id_sizes');
    M.FormSelect.init(selectEl);
  </script>

{% endblock %}

main_app/templates/main_app/laces_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Laces List</h1>

{% for lace in laces_list %}
  <a href="{% url 'laces_detail' lace.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">Size: {{ lace.sizes }}</span>
            <p>Color: {{ lace.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/sneaker_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Sneaker</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/sneaker_form.html
{% extends 'base.html' %}


{% block content %}
<!-- Leaving the action blank will use the same url that was used in order to get the form -->
	{% if object %}
	<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
	{% else %}
	<h1>Add Sneaker</h1>
	{% endif %}

	<form action="" method="POST">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>

		<input type="submit" value="submit!" class="btn" />
	</form>

	<script>
		const selectEl = document.getElementById('id_laces');
		M.FormSelect.init(selectEl);
	</script>
	
  
{% endblock content %}

main_app/templates/sneakers/detail.html
{% extends 'base.html' %}


{% block content %}
    
<h1>Sneaker Details</h1>

<div class="card">
    <div class="card-content">
      <span class="card-title">{{ sneaker.name }}</span>
      <p>Brand: {{ sneaker.brand }}</p>
      <p>Description: {{ sneaker.description }}</p>
      <p>Retail Price: {{ sneaker.price }}</p>
    </div>
    <div class="card-action">
        <a href="{% url 'sneakers_update' sneaker.id %}">Edit</a>
        <a href="{% url 'sneakers_delete' sneaker.id %}">Delete</a>
    </div>
  </div>
  <div class="col s6">
    <form method="post" action="{% url 'add_buyer' sneaker.id %}">
        {% csrf_token %}
        {{ buyer_form.as_p }}
        <input type="submit" class="btn" value="Add Buyer">
      </form>
    <table class="striped">
      <thead>
        <tr><th>Name</th><th>Resell Value</th><th>Date Bought</th><th>Size</th></tr>
      </thead>
      <tbody>
        {% for buyer in sneaker.buyer_set.all %}
          <tr>
            <td>{{buyer.name}}</td>
            <td>{{buyer.value}}</td>
            <td>{{buyer.bought}}</td>
            <td>{{buyer.size}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ sneaker.name }}'s Laces</h3>
      {% if sneaker.laces.count %}
        {% for lace in sneaker.laces.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                This Shoe has {{ lace.color }} size {{lace.sizes}} Laces!
              </span>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No Laces Bought</h5>
      {% endif %}
    </div>
    <div class="col s6">
      <h3>Available Laces</h3>
      {% if laces.count %}
        {% for lace in laces.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                {{ lace.color }} Size {{ lace.sizes }} Laces
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_lace' sneaker.id lace.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{lace.sizes}} All Laces are Taken</h5>
      {% endif %}
    </div>

<script>
    const dateEl = document.getElementById('id_bought');
    M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_size');
  M.FormSelect.init(selectEl);

</script>

{% endblock %}

main_app/templates/sneakers/index.html
{% extends 'base.html' %}


{% block content %}

<h1>Sneaker List</h1>


{% for sneaker in sneakers %}
<a href="{% url 'detail' sneaker.id %}">
<div class="card">
    <div class="card-content">
      <span class="card-title">{{ sneaker.name }}</span>
      <p>Brand: {{ sneaker.brand }}</p>
      <p>Description: {{ sneaker.description }}</p>
      <p>Retail Price: {{ sneaker.price }}</p>
    </div>
  </div>
</a>
{% endfor %}
	

{% endblock %}
	